denemenet/Models/Tables/katagori.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace denemenet.Models.Tables
{
    [Table("Kategori")]
    public class katagori
    {
       public katagori()
        {
            urun = new HashSet<urun>();
       }

        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int ID { get; set; }

        [Required]
        [StringLength(100)]
        public string name { get; set; }

        [Required]
        [StringLength(100)]
        public string link { get; set; }

        [Required]
        [StringLength(100)]
        public string resim { get; set; }


        public virtual ICollection<urun> urun { get; set; }






    }
}

denemenet/Models/Tables/urun.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace denemenet.Models.Tables
{
    [Table("urun")]
    public class urun
    {
        //public urun()
        //{
        //    resim1 = new HashSet<resim>();
        //}

        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int id { get; set; }

        [StringLength(100)]
        public string Adi { get; set; }

        public int? Fiyat { get; set; }

        [StringLength(100)]
        public string Resim { get; set; }

        public int? katagoriID { get; set; }

        public virtual katagori katagori { get; set; }
        
        
        public virtual ICollection<resims> resim1 { get; set; }
        public virtual ICollection<mesaj> mesajs { get; set; }






    }
}

denemenet/Controllers/KatagoriController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace denemenet.Controllers
{
    public class KatagoriController : Controller
    {
        // GET: Katagori
        public ActionResult İndex()
        {
            return View();
        }
    }
}

denemenet/Controllers/adminEWDController.cs
using denemenet.Models;
using denemenet.Models.Tables;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace denemenet.Controllers
{

    public class adminEWDController : Controller
    {
        ContextDb db = new ContextDb();
        [Authorize]
        public ActionResult ewdLayout() { return View(); }
        // GET: adminEWD
        /*//////////////////////////////// yeni kayıtlar/////////////////////////////////// */
        [Authorize] public ActionResult newurun() { return View(); }
        [Authorize] public ActionResult newkatagori() {
            
            
            return View(); }

        [Authorize] public ActionResult newyorum() { return View(); }
        [Authorize] public ActionResult newresim() { return View(); }
        /*//////////////////////////////// kayıt silme/////////////////////////////////// */
        [Authorize]
        public ActionResult urundelete(int? id)
        {
            urun urun = new urun();
            urun = db.UrunTablosu.Where(x => x.id == id).FirstOrDefault();
            if (urun != null) { return View(urun); }
            else { return RedirectToAction("Urun", "admin"); }
        }


        [Authorize]
        public ActionResult katagoridelete(int? id)
        {
            katagori katagori = new katagori();
            katagori = db.KatagoriTablosu.Where(x => x.ID == id).FirstOrDefault();

            if (katagori != null) { return View(katagori); }
            else { return RedirectToAction("Katagori", "admin"); }
        }
        [Authorize]
        public ActionResult yorumdelete(int? id)
        {
            mesaj mesaj = new mesaj();
            mesaj = db.MesajTablosu.Where(x => x.ID == id).FirstOrDefault();
            if (mesaj != null) { return View(mesaj); }
            else { return RedirectToAction("yorum", "admin"); }

        }
        [Authorize]
        public ActionResult urunedit(int? id)
        {
            urun urun = new urun();
            urun = db.UrunTablosu.Where(x => x.id == id).FirstOrDefault();


            if (urun != null) { return View(urun); }
            else { return RedirectToAction("urun", "admin"); }
        }
        [Authorize]
        public ActionResult katagoriedit(int? id)
        {
            katagori katagori = new katagori();
            katagori = db.KatagoriTablosu.Where(x => x.ID == id).FirstOrDefault();

            if (katagori != null) { return View(katagori); }
            else { return RedirectToAction("Katagori", "admin"); }
        }
        [Authorize]
        public ActionResult yorumedit(int? id)
        {
            mesaj mesaj = new mesaj();
            mesaj = db.MesajTablosu.Where(x => x.ID == id).FirstOrDefault();

            if (mesaj != null) { return View(mesaj); }
            else { return RedirectToAction("yorum", "admin"); }
        }

        /*/////////////////////////////////////////////////////////////////////*/
        [HttpPost, ActionName("urundelete")]
        [Authorize]
        public ActionResult urundeleteactive(int? id)
        {

            urun urun = db.UrunTablosu.Where(x => x.id == id).FirstOrDefault();
         
            List<resims> resimsListesi = db.ResimTablosu.Where(y => y.urun.id == id).ToList();
            List<mesaj> mesajListesi = db.MesajTablosu.Where(y => y.urun.id == id).ToList();
            foreach (var item in resimsListesi)
            {
                db.ResimTablosu.Remove(item);
            }
            foreach (var msj in mesajListesi)
            {
                db.MesajTablosu.Remove(msj);
            }
            db.UrunTablosu.Remove(urun);
            db.SaveChanges();
            return RedirectToAction("Urun", "admin");
        }
        [Authorize]
        [HttpPost,ActionName("newkatagori")]
        public ActionResult newkatagoriactive(katagori katagori)
        {
            katagori.link = FakeData.NameData.GetFirstName();
            katagori.resim = "katagori"+FakeData.NumberData.GetNumber(0, 4)+ ".jpg"; 
            db.KatagoriTablosu.Add(katagori);
            int sonuc = db.SaveChanges();
            if (sonuc > 0)
            {
                return RedirectToAction("katagori", "admin");
            }
            else
            {
                return View();
            }
        }
        [Authorize]
        [HttpPost, ActionName("newurun")]
        public ActionResult newurunactive(urun urun)
        {
          
            
            urun.Fiyat = FakeData.NumberData.GetNumber(0, 50);

            urun.Resim = "urunresim" + FakeData.NumberData.GetNumber(0, 9) + ".jpg";
          

            db.UrunTablosu.Add(urun);
            int sonuc = db.SaveChanges();
            if (sonuc > 0)
            {
                return RedirectToAction("Urun", "admin");
            }
            else
            {
                return View();
            }
        }

        [Authorize]
        [HttpPost, ActionName("katagoridelete")]
        public ActionResult katagorideleteactive(int? id)
        {
            if (id != null)
            {
                katagori katagori = db.KatagoriTablosu.Where(x => x.ID == id).FirstOrDefault();
                // Kişi kaydını silmeden önce ilişkili tablolardaki kayıtları silmeliyiz
                List<urun> urunListesi = db.UrunTablosu.Where(y => y.katagori.ID == id).ToList();
                List<resims> resimsListesi = db.ResimTablosu.Where(y => y.urun.katagori.ID == id).ToList();
                List<mesaj> mesajListesi = db.MesajTablosu.Where(y => y.urun.katagori.ID == id).ToList();
                foreach (var item in resimsListesi)
                {
                    db.ResimTablosu.Remove(item);
                }
                foreach (var item in mesajListesi)
                {
                    db.MesajTablosu.Remove(item);
                }
                foreach (var item in urunListesi)
                {
                    db.UrunTablosu.Remove(item);
                }
                db.KatagoriTablosu.Remove(katagori);
                db.SaveChanges();
            }
            return RedirectToAction("katagori", "admin");
        }
        [Authorize]
        [HttpPost, ActionName("yorumdelete")]
        public ActionResult yorumdeleteactive(int? id)
        {

            mesaj mesaj = db.MesajTablosu.Where(x => x.ID == id).FirstOrDefault();
            // Kişi kaydını silmeden önce ilişkili tablolardaki kayıtları silmeliyiz

            db.MesajTablosu.Remove(mesaj);
            db.SaveChanges();
            return RedirectToAction("yorum", "admin");
        }
        [Authorize]
        [HttpPost, ActionName("urunedit")]
        public ActionResult uruneditactive(int? id, urun urun)
        {
            int sonuc = 0;
            urun urunR = db.UrunTablosu.Where(x => x.id == id).FirstOrDefault();
            if (urunR != null)
            {
                urunR.Adi = urun.Adi;
                urunR.katagoriID = urun.katagoriID;

                sonuc = db.SaveChanges();
            }
            if (sonuc > 0)
            {
                return RedirectToAction("Urun", "admin");
            }
            else
            {
                return View();
            }

        }
        [Authorize]
        [HttpPost, ActionName("katagoriedit")]
        public ActionResult katagorieditactive(int? id, katagori katagori)
        {
            int sonuc = 0;
            katagori katagoriR = db.KatagoriTablosu.Where(x => x.ID == id).FirstOrDefault();
            if (katagoriR != null)
            {
                katagoriR.name = katagori.name;


                sonuc = db.SaveChanges();
            }
            if (sonuc > 0)
            {
                return RedirectToAction("Katagori", "admin");
            }
            else
            {
                return View();
            }

        }
        [Authorize]
        [HttpPost, ActionName("yorumedit")]
        public ActionResult yorumeditactive(int? id, mesaj mesaj)
        {
            int sonuc = 0;
            mesaj mesajR = db.MesajTablosu.Where(x => x.ID == id).FirstOrDefault();
            if (mesajR != null)
            {
                mesajR.name = mesaj.name;
                mesajR.text = mesaj.text;



                sonuc = db.SaveChanges();
            }
            if (sonuc > 0)
            {
                return RedirectToAction("yorum", "admin");
            }
            else
            {
                return View();
            }

        }
    }



}

denemenet/Controllers/urunController.cs
using denemenet.Models;
using denemenet.Models.Tables;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
//using denemenet.Models.Entity;
namespace denemenet.Controllers
{

    public class urunController : Controller
    {
        ContextDb db = new ContextDb();
        UrunModelView model = new UrunModelView();
        urun Tekurun = new urun();
        detayViewModel detayModel = new detayViewModel();
        public ActionResult urunler(int? id)
        {


            //  var deger = from d in db.UrunTablosu select d;
            //deger = deger.Where(m => m.katagoriID == id);

            model.UrunListesi = db.UrunTablosu.Where(m => m.katagoriID == id).ToList(); ;

            model.ResimListesi = db.ResimTablosu.Where(m => m.urun.katagoriID == id).ToList();
            if (model.UrunListesi.Count > 0) { ViewData["resim"] = "/image/urun_resim/" + model.UrunListesi.FirstOrDefault().Resim;
                ViewData["Baslik"] = model.UrunListesi.FirstOrDefault().katagori.name; }
            else {
                ViewData["resim"] = "/image/detakatagoriresim/" + db.KatagoriTablosu.Where(m => m.ID == id).FirstOrDefault().resim;
                ViewData["Baslik"] = db.KatagoriTablosu.Where(m => m.ID == id).FirstOrDefault().name; }

           

            foreach (var urn in model.UrunListesi)
            {

                ViewData["Baslik"] = urn.katagori.name;

                break;
            }

            return View(model);
        }
        public ActionResult katagori()
        {
            model.KatagoriListesi = db.KatagoriTablosu.ToList();
            model.ResimListesi = db.ResimTablosu.ToList();
            ViewData["Baslik"] = "TAVUK CİNSLERİ";
            ViewData["resim"] = "/image/detakatagoriresim/" + model.KatagoriListesi.FirstOrDefault().resim;
            return View(model);

        }
        public ActionResult detayurun(int? id)
        {


            //  var deger = from d in db.ResimTablosu select d;
            // deger = deger.Where(m => m.urunID == id);
            // detayModel.UrunListesi = db.ResimTablosu.ToList();
            detayModel.ResimListesi = db.ResimTablosu.Where(m => m.urunID == id).ToList();
            detayModel.MesajListesi = db.MesajTablosu.Where(m => m.urunID == id).ToList();

            Tekurun = db.UrunTablosu.Where(x => x.id == id).FirstOrDefault();
            ViewData["resim"] = "/image/urun_resim/" + Tekurun.Resim;
            ViewData["Baslik"] = Tekurun.katagori.name + "\n";
            ViewData["AltBaslik"] = Tekurun.Adi;
            TempData["id"] = id;
            ViewBag.urun = Tekurun;






            return View(detayModel);
        }
        class SendData
        {
            public string mail { get; set; }
            public string text { get; set; }
            public string name { get; set; }
        }

        [HttpPost]
        public JsonResult CommentsPost(mesaj MessageComments)
        {
            mesaj msg = new mesaj();
            //   Response.Redirect("GOOGLE.COM.TR");
            msg.urunID = (int)TempData["id"];
            msg.name = MessageComments.name;
            msg.text = MessageComments.text;
            msg.replyid = FakeData.NumberData.GetNumber(51, 99);
            msg.replytext = FakeData.TextData.GetSentences(2);
            msg.mail = MessageComments.mail;
            msg.Time = DateTime.Now.Date;
            string message = "";
            try
            {
                message = "Ekleme Başarılı En Kısa Zamanda Onaylanacaktır.";
                db.MesajTablosu.Add(msg);
                db.SaveChanges();
            }
            catch (Exception ex) { message = ex.ToString(); }

            TempData["id"] = msg.urunID;
            return Json(message);

        }


    }
}

denemenet/Views/admin/Katagori.cshtml
@model denemenet.Models.UrunModelView
@{
    ViewBag.Title = "Katagori";
    Layout = "~/Views/admin/AdminLayout.cshtml";
}

<div class="">



    <div class="row">
        <div class="col-md-12 col-sm-12 ">
            <div class="x_panel">
                <div class="x_title">
                    <h2>
                        KATEGORİ TABLOSU
                        <br />
                        KATEGORİ SAYISI: @Model.KatagoriListesi.Count

                    </h2> 
                    <ul class="nav navbar-right panel_toolbox">
                        <li>
                            <a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                        </li>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                <a class="dropdown-item" href="#">Settings 1</a>
                                <a class="dropdown-item" href="#">Settings 2</a>
                            </div>
                        </li>
                        <li>
                            <a class="close-link"><i class="fa fa-close"></i></a>
                        </li>
                    </ul>
                    <div class="clearfix"></div>
                </div>


                <div class="x_content">
              
                    <div class="row">
                        @Html.ActionLink("Yeni Ekle", "newkatagori", "adminEWD", new { }, new { @class = "btn btn-success" })
                        <div class="col-sm-12">
                            <div class="card-box table-responsive">
                                <p class="text-muted font-13 m-b-30">
                                    HIZLI GÖSTERİM KATEGORİ
                                </p>

                                <table id="datatable-responsive" class="table table-striped table-bordered dt-responsive nowrap" cellspacing="0" width="100%">

                                    <thead>
                                        <tr>
                                            <th>ÜRÜN İD</th>
                                            <th>ÜRÜN ADI</th>
                                            <th>KATAGORİ</th>
                                            <th></th>




                                        </tr>
                                    </thead>

                                    <tbody>
                                        @foreach (var ktgr in Model.KatagoriListesi)
                                        {


                                            <tr>
                                                <td>@ktgr.ID</td>
                                                <td>@ktgr.name</td>


                                                @*<td>  <a href="#" class="btn btn-primary btn-xs"><i class="fa fa-folder"></i> View </a></td>*@


                                                <td>    <a href="@Url.Action("katagoriedit","adminEWD",new { id=ktgr.ID })" class="btn btn-info btn-xs"><i class="fa fa-pencil"></i> Edit </a></td>
                                                <td>  <a href="@Url.Action("katagoridelete","adminEWD",new { id=ktgr.ID })" class="btn btn-danger btn-xs"><i class="fa fa-trash-o"></i> SİL </a></td>

                                            </tr>
                                        }

                                    </tbody>

                                </table>


                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

denemenet/Views/admin/Login.cshtml
@{
    Layout = null;
}


<!DOCTYPE html>

<html>
<head>
    <link rel="stylesheet" href="~/Content/adminCss.css" />
    <meta name="viewport" content="width=device-width" />
    <title>Login</title>
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
</head>
<body>
    <div class="wrapper fadeInDown">
        <div id="formContent">

            <div class="fadeIn first">
                <img src="~/image/logo.png" id="icon" alt="Admin Icon" />
            </div>


            <form>
                <input type="text" id="login" class="fadeIn second" name="login" placeholder="Kullanıcı" required>
                <input type="text" id="password" class="fadeIn third" name="login" placeholder="Parola" required>
                <input type="submit" class="fadeIn fourth" value="Giriş Yap">
            </form>

       
        </div>
    </div>
</body>
</html>

denemenet/Views/admin/Urun.cshtml
@model denemenet.Models.UrunModelView

@section AddToHead{

    <link href="cdn.datatables.net/1.10.20/css/jquery.dataTables.min.css">
    <link href="~/AdminTemplate/vendors/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet">

    <link href="~/AdminTemplate/vendors/font-awesome/css/font-awesome.min.css" rel="stylesheet">

    <link href="~/AdminTemplate/vendors/nprogress/nprogress.css" rel="stylesheet">

    <link href="~/AdminTemplate/vendors/iCheck/skins/flat/green.css" rel="stylesheet">


    <link href="~/AdminTemplate/vendors/datatables.net-bs/css/dataTables.bootstrap.min.css" rel="stylesheet">
    <link href="~/AdminTemplate/vendors/datatables.net-buttons-bs/css/buttons.bootstrap.min.css" rel="stylesheet">
    <link href="~/AdminTemplate/vendors/datatables.net-fixedheader-bs/css/fixedHeader.bootstrap.min.css" rel="stylesheet">
    <link href="~/AdminTemplate/vendors/datatables.net-responsive-bs/css/responsive.bootstrap.min.css" rel="stylesheet">
    <link href="~/AdminTemplate/vendors/datatables.net-scroller-bs/css/scroller.bootstrap.min.css" rel="stylesheet">

    <!-- Custom Theme Style -->
    <link href="~/AdminTemplate/build/css/custom.min.css" rel="stylesheet">
}
@{
    //Layout = null;
    ViewBag.Title = "Urun";
    Layout = "~/Views/admin/AdminLayout.cshtml";






}

<!DOCTYPE html>
<html lang="en">
<head>

</head>

<body class="nav-md">
    <div class="">



        <div class="row">
            <div class="col-md-12 col-sm-12 ">
                <div class="x_panel">
                 
                    <div class="x_title">
                        <h2>
                            ÜRÜNLER  TABLOSU <br />
                            ÜRÜN SAYISI:  @Model.UrunListesi.Count
                        </h2>
                        <ul class="nav navbar-right panel_toolbox">
                            <li>
                                <a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                            </li>
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                                <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                    <a class="dropdown-item" href="#">Settings 1</a>
                                    <a class="dropdown-item" href="#">Settings 2</a>
                                </div>
                            </li>
                            <li>
                                <a class="close-link"><i class="fa fa-close"></i></a>
                            </li>
                        </ul>
                        <div class="clearfix"></div>
                    </div>


                    <div class="x_content">
                        <div class="row">
                            @Html.ActionLink("Yeni Ekle", "newurun", "adminEWD",new { } ,new { @class = "btn btn-success" })
                            <div class="col-sm-12">
                                <div class="card-box table-responsive">
                                    <p class="text-muted font-13 m-b-30">
                                        ÜRÜNLER TABLOSUNDA HIZLI ARAMA :SEARCH BULUNMAKTADIR
                                    </p>

                                    <table id="datatable-responsive" class="table table-striped table-bordered dt-responsive nowrap" cellspacing="0" width="100%">

                                        <thead>
                                            <tr>
                                                <th>ÜRÜN İD</th>
                                                <th>ÜRÜN ADI</th>
                                                <th>KATAGORİ</th>
                                                <th></th>
                                                <th></th>
                                                <th> </th>


                                            </tr>
                                        </thead>

                                        <tbody>
                                            @foreach (var urn in Model.UrunListesi)
                                            {


                                                <tr>
                                                    <td>@urn.id</td>
                                                    <td>@urn.Adi</td>
                                                    <td>@urn.katagori.name</td>

                                                    @*<td>  <a href="#" class="btn btn-primary btn-xs"><i class="fa fa-folder"></i> View </a></td>*@


                                                    <td>    <a href="@Url.Action("urunedit","adminEWD",new { id=urn.id })" class="btn btn-info btn-xs"><i class="fa fa-pencil"></i> GÜNCELLE </a></td>
                                                    <td>  <a href="@Url.Action("urundelete","adminEWD",new { id=urn.id })" class="btn btn-danger btn-xs"><i class="fa fa-trash-o"></i> SİL </a></td>
                                                    <td>@urn.Resim</td>
                                                </tr>
                                            }

                                        </tbody>

                                    </table>


                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- jQuery -->


</body>
</html>

denemenet/Views/admin/yorum.cshtml
@model denemenet.Models.detayViewModel
@{
    ViewBag.Title = "yorum";
    Layout = "~/Views/admin/AdminLayout.cshtml";
}

<div class="">



    <div class="row" style="max-height:1000px">
        <div class="col-md-12 col-sm-12 ">
            <div class="x_panel">
                <div class="x_title">
                    <h2>MESAJ TABLOSU <br />
                   Mesaj Sayısı: @Model.MesajListesi.Count  
                   </h2>
                    <ul class="nav navbar-right panel_toolbox">
                        <li>
                            <a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                        </li>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                <a class="dropdown-item" href="#">Settings 1</a>
                                <a class="dropdown-item" href="#">Settings 2</a>
                            </div>
                        </li>
                        <li>
                            <a class="close-link"><i class="fa fa-close"></i></a>
                        </li>
                    </ul>
                    <div class="clearfix"></div>
                </div>


                <div class="x_content">
                    <div class="row">
                        <div class="col-sm-12">
                            <div class="card-box table-responsive">
                                <p class="text-muted font-13 m-b-30">
                                   Hızlı MESAJ TABLOSU 
                                </p>

                                <table id="datatable-responsive" class="table table-striped table-bordered dt-responsive nowrap" cellspacing="0" width="100%">

                                    <thead>
                                        <tr>

                                            <th>Mesaj İD</th>
                                            <th>ÜRÜN</th>
                                            <th>YAYINDA</th>
                                            <th>GÖNDEREN</th>
                                            <th>MAİL</th>

                                            <th>ZAMAN </th>
                                            <th> </th>
                                            <th> </th>
                                        

                                        </tr>
                                    </thead>

                                    <tbody>
                                        @foreach (var urn in Model.MesajListesi)
                                        {


                                        <tr>
                                            <td>@urn.ID</td>
                                            <td>@urn.urun.Adi</td>
                                            <td>AKTİF</td>
                                            <td>@urn.name</td>
                                            <td>@urn.mail</td>
                                            <td>@urn.Time</td>
                                            @*<td>  <a href="#" class="btn btn-primary btn-xs"><i class="fa fa-folder"></i> View </a></td>*@


                                            <td>    <a href="@Url.Action("yorumedit","adminEWD",new { id=urn.ID })" class="btn btn-info btn-xs"><i class="fa fa-pencil"></i> Edit </a></td>
                                            <td>  <a href="@Url.Action("yorumdelete","adminEWD",new { id=urn.ID })" class="btn btn-danger btn-xs"><i class="fa fa-trash-o"></i> Delete </a></td>


                                        </tr>
                                        }

                                    </tbody>

                                </table>


                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>